theme: minima
title: What up, folks?
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Well as you all know, I write nothing but interesting and incredibly funny content
  always so check this out from time to time to be updated about the newest and more
  useful tips and guidelines about every new framework and language.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
